; SCENE_3_ACT_3.Z80
;
; Map Source File.
;
; Info:
;   Section       : scene_3_act_3
;   Bank          : 0
;   Map size      : 32 x 32
;   Tile set      : Z:\home\cpc\RA\RA\AHMBAR\src\assets\tiles\sonia\MapaTiles.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 128
;   Split data    : No
;
; This file was generated by GBMB v1.8

 SECTION "act_3_scene_3_sonia", ROMX

act_3_scene_3_sonia::
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$90,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E8,$E5,$E5,$E5,$E5,$E5,$E9,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$90
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $E6,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E5,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$E8,$E5,$E5,$E5,$E5,$E5
DB $E5,$E5,$E5,$E9,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$E5,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$E5,$E5,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$E5
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $E5,$E5,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E5,$E5,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$E6,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$E5,$8C,$8C,$8C,$8C,$8C
DB $8C,$C0,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$E7,$8C,$8C,$8C
DB $8C,$8C,$8C,$C1,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E6,$8C,$8C,$8C,$8C,$8C,$8C,$E5
DB $8C,$92,$90,$90,$90,$90,$91,$8C,$8C,$8C
DB $8C,$8C,$8C,$92,$90,$90,$90,$91,$8C,$8C
DB $8C,$8C,$8C,$8C,$E5,$8C,$8C,$B3,$B1,$B2
DB $8C,$E5,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$B3,$B1,$B2,$8C,$E5,$8C,$8C,$8C
DB $8C,$8C,$8C,$E7,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $E5,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E8,$E5,$E5,$E5,$E5,$E5,$E5,$E9
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E5,$8C,$E8,$E5,$E5,$E5,$E9,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$E7,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$E6,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$99,$9A,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$B3,$B1,$B2,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$9B,$9C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$99,$9A,$99,$9A,$8C,$E5
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$9B
DB $9C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$99,$9A,$8C,$9B,$9C,$9B,$9C
DB $8C,$E5,$8C,$8C,$8C,$8C,$8C,$99,$9A,$8C
DB $8C,$9B,$9C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$99,$9A,$8C,$9B,$9C,$8C,$9B,$9C
DB $9B,$9C,$8C,$E7,$8C,$8C,$99,$9A,$8C,$9B
DB $9C,$8C,$8C,$9B,$9C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$9D,$9E,$8C,$9D,$9E,$8C
DB $9D,$9E,$9D,$9E,$8C,$8C,$8C,$8C,$9D,$9E
DB $8C,$9D,$9E,$8C,$8C,$9D,$9E,$8C,$8C,$92
DB $90,$90,$90,$91

; End of SCENE_3_ACT_3.Z80
