; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : butterflies
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Butterfly Tiles", ROM0

; Start of tile array.
butterfly_tiles::
.start:
DB $66,$66,$DB,$BD,$99,$FF,$5A,$7E
DB $99,$FF,$DB,$BD,$99,$FF,$66,$66
.end:

; End of EXPORT.Z80
