; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Dark frog tile", ROM0

; Start of tile array.
dark_frog_tile::
.start:
DB $30,$30,$68,$78,$F4,$DC,$FA,$FE
DB $7D,$7F,$7F,$7F,$4F,$7F,$5E,$7E
.end:

; End of EXPORT.Z80
