; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 2
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Enemy desintegration tiles", ROM0

; Start of tile array.
desintegration_tiles::
.start:
DB $00,$00,$00,$00,$28,$18,$78,$50
DB $24,$1C,$18,$20,$00,$00,$00,$00
DB $00,$00,$08,$08,$2C,$18,$70,$64
DB $00,$58,$7C,$54,$10,$30,$00,$00
DB $00,$00,$42,$41,$A0,$80,$60,$64
DB $00,$40,$75,$45,$90,$31,$00,$00
.end:

; End of EXPORT.Z80
