; FALLING_ROCK.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Rock Tile
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Rock Tile", ROM0

; Start of tile array.
rock_tile::
.start:
DB $76,$6E,$A1,$DF,$8D,$7B,$A3,$DD
DB $D2,$BF,$2D,$D3,$85,$FF,$7A,$6E
.end:

; End of FALLING_ROCK.Z80
