; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 3
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROM0

; Start of tile array.
TilesSoniaPrueba::
DB $00,$00,$FF,$FF,$81,$81,$BD,$BD
DB $BD,$BD,$81,$81,$FF,$FF,$00,$00

DB $7E,$7E,$42,$42,$5A,$5A,$5A,$5A
DB $5A,$5A,$5A,$5A,$42,$42,$7E,$7E

DB $10,$10,$28,$28,$44,$44,$9A,$9A
DB $59,$59,$22,$22,$14,$14,$08,$08

DB $08,$08,$14,$14,$22,$22,$59,$59
DB $9A,$9A,$44,$44,$28,$28,$10,$10

; End of EXPORT.Z80
