; SCENE2_ACT_3_SONIA.Z80
;
; Map Source File.
;
; Info:
;   Section       : scene2_act_3_sonia
;   Bank          : 0
;   Map size      : 32 x 32
;   Tile set      : Z:\home\cpc\RA\RA\AHMBAR\src\assets\tiles\sonia\MapaTiles.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 128
;   Split data    : No
;
; This file was generated by GBMB v1.8



SECTION FRAGMENT "Tile Maps", ROMX

act_3_scene_2_tilemap::
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $E8,$E5,$E5,$E5,$E5,$E5,$E5,$E5,$E9,$8C
DB $8C,$8C,$8C,$C0,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$C1,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$92,$90,$90,$90,$91
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$91,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E6
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$E5,$8C,$8C,$8C,$8C,$8C,$E8,$E5,$E5
DB $E9,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$E5,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$E5,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E7
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$90,$8C
DB $8C,$8C,$8C,$E8,$E5,$E9,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E8,$E5,$E5,$E5,$E5,$E9,$8C,$8C
DB $8C,$8C,$E6,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$E8,$E5,$E5,$E5,$E5
DB $E5,$E5,$E9,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$E5,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$90,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E5,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $E5,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$E7,$8C,$8C,$90,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$90,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$90,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $92,$90,$90,$90,$90,$91,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C
DB $8C,$8C,$8C,$8C,$8C,$8C,$8C,$8C,$E1,$E1
DB $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
DB $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
DB $E1,$E1,$E1,$E1

; End of SCENE2_ACT_3_SONIA.Z80
