; SCENE2_ACT_3_SONIA.Z80
;
; Map Source File.
;
; Info:
;   Section       : scene2_act_3_sonia
;   Bank          : 0
;   Map size      : 32 x 32
;   Tile set      : Z:\home\cpc\RA\RA\AHMBAR\src\assets\tiles\sonia\MapaTiles.gbr
;   Plane count   : 1 plane (8 bits)
;   Plane order   : Tiles are continues
;   Tile offset   : 128
;   Split data    : No
;
; This file was generated by GBMB v1.8



SECTION FRAGMENT "Tile Maps", ROMX

act_3_scene_2_tilemap::
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$E8,$E5,$E5,$E5,$E5,$E5,$E5,$E9,$8D
DB $8D,$8D,$8D,$C4,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$C5,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$92,$92,$92,$92,$92
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$92,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $E6,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$E5,$8D,$8D,$8D,$8D,$8D,$8D,$E8
DB $E5,$E5,$E9,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$E5,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$E5,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$E7,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$92,$8D,$8D
DB $8D,$8D,$8D,$E8,$E5,$E9,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $E8,$E5,$E5,$E5,$E5,$E5,$E9,$8D,$8D,$8D
DB $8D,$E6,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$E8,$E5,$E5,$E5,$E5
DB $E5,$E9,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$E5,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$E5,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$E5,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$92,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$E5
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$E5,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$E5,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$92,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$92,$8D,$8D,$8D,$E7,$8D,$8D,$92,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $92,$92,$92,$92,$92,$E1,$E1,$E1,$E1,$E1
DB $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
DB $E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1,$E1
DB $E1,$E1,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D,$8D
DB $8D,$8D,$8D,$8D


; End of SCENE2_ACT_3_SONIA.Z80
