; EXPORT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Electricity animatio
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 4
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Electricity animation", ROM0

; Start of tile array.
electricity_animation_tiles::
.vertical_electricity_1:
DB $D7,$00,$6B,$00,$DA,$00,$F6,$00
DB $5B,$00,$BD,$00,$BA,$00,$D5,$00
.horizontal_electricity_1:
DB $55,$00,$AB,$00,$EB,$00,$D6,$00
DB $5B,$00,$6B,$00,$DA,$00,$BD,$00
.vertical_electricity_2:
DB $ED,$00,$7E,$00,$91,$00,$6F,$00
DB $9B,$00,$65,$00,$BE,$00,$73,$00
.horizontal_electricity_2:
DB $ED,$00,$9F,$00,$62,$00,$BD,$00
DB $76,$00,$A9,$00,$5F,$00,$B3,$00
.end:
; End of EXPORT.Z80
