INCLUDE "constants.inc"

SECTION "Level 3 Map", ROM0

Level3_Map::
    ; Fila sin objetivo (movido al centro)
    DS 32, TILE_EMPTY

    ; Diseño tipo laberinto superior
    DB TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_BRICK
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    ; Ventanas decorativas
    DB TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Tuberías cruzadas
    DB TILE_PIPE,TILE_PIPE,TILE_PIPE,TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_CABLE
    DB TILE_CABLE,TILE_EMPTY,TILE_EMPTY,TILE_PIPE,TILE_PIPE,TILE_PIPE,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_CABLE,TILE_EMPTY,TILE_EMPTY,TILE_PIPE
    DB TILE_PIPE,TILE_PIPE,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_CABLE

    DS 32, TILE_EMPTY

    ; Plataformas escalonadas
    DB TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS
    DB TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Más plataformas
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Fila con el cuadrado objetivo en el centro (columna 16)
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_GOAL,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    ; Ladrillos y ventanas alternados
    DB TILE_BRICK,TILE_WINDOW,TILE_BRICK,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_BRICK,TILE_WINDOW,TILE_BRICK,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_BRICK,TILE_WINDOW,TILE_BRICK,TILE_WINDOW
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Advertencias distribuidas
    DB TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WARNING

    ; Suelo
    DS 32, TILE_GROUND

Level3_Map_End::

Load_Level3_Map::
    ld hl, Level3_Map
    ld de, $9800
    ld bc, Level3_Map_End - Level3_Map
    call Copy_Memory
    ret
