INCLUDE "constants.inc"

SECTION "Level 2 Map", ROM0

Level2_Map::
    DS 32, TILE_EMPTY

    ; Fila sin objetivo (movido al centro)
    DS 32, TILE_EMPTY

    ; Plataformas superiores
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_BRICK,TILE_BRICK,TILE_BRICK,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_BRICK,TILE_BRICK,TILE_BRICK
    DB TILE_BRICK,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Tuberías y cables
    DB TILE_CABLE,TILE_CABLE,TILE_EMPTY,TILE_EMPTY,TILE_PIPE,TILE_PIPE,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_EMPTY,TILE_EMPTY,TILE_PIPE,TILE_PIPE
    DB TILE_PIPE,TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_PIPE,TILE_PIPE,TILE_EMPTY,TILE_EMPTY,TILE_CABLE,TILE_CABLE,TILE_EMPTY

    DS 32 * 2, TILE_EMPTY

    ; Plataformas medias
    DB TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS
    DB TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Ventanas y ladrillos
    DB TILE_WINDOW,TILE_BRICK,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_BRICK,TILE_WINDOW,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WINDOW,TILE_BRICK
    DB TILE_WINDOW,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Fila con el cuadrado objetivo en el centro (columna 16)
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_GOAL,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    ; Más plataformas bajas
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_PLATFORM_LIGHTS,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    DS 32, TILE_EMPTY

    ; Advertencias
    DB TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_WARNING,TILE_WARNING,TILE_EMPTY
    DB TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY
    DB TILE_WARNING,TILE_WARNING,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY,TILE_EMPTY

    ; Suelo
    DS 32, TILE_GROUND

Level2_Map_End::

Load_Level2_Map::
    ld hl, Level2_Map
    ld de, $9800
    ld bc, Level2_Map_End - Level2_Map
    call Copy_Memory
    ret
