; BULLETS.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Bullet Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 2
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "Bullet Tiles", ROM0

; Start of tile array.
bullet_tiles::
.bullet_hud_tile:
DB $00,$00,$7C,$7C,$7E,$52,$51,$7F
DB $51,$7F,$52,$7E,$7C,$7C,$00,$00
.bullet_tile:
DB $00,$00,$00,$00,$7C,$7C,$7E,$52
DB $7C,$7C,$00,$00,$00,$00,$00,$00
.bullet_box:
DB $FE,$FE,$41,$7F,$FF,$AB,$FD,$D7
DB $85,$FF,$B5,$EF,$85,$FF,$FE,$FE
.end:
; End of BULLETS.Z80
