; PLAYER.Z80
;
; Tile Source File.
;
; Info:
;   Section              : player_beta_tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 2
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Player beta tiles", ROM0

; Start of tile array.
player_beta_tiles::
.start:
DB $3E,$3E,$3E,$30,$3E,$30,$5F,$7F
DB $73,$6E,$8A,$FE,$B8,$FF,$C7,$C7
DB $7C,$7C,$7C,$60,$7C,$60,$7E,$7E
DB $76,$6C,$54,$7C,$48,$7C,$7C,$7C
DB $BE,$BE,$FE,$F0,$BE,$B0,$FF,$BE
DB $62,$7E,$42,$7E,$5A,$7E,$66,$66
.end:
; End of PLAYER.Z80
